quarkus:
  http:
    port: 8081
  mongodb:
    connection-string: mongodb://mongo.test:27017
    database: people

camel:
  context:
    name: protobuf-consumer

rabbitmq:
  url: localhost:5672
  vhost: /
  queue: people
  username: guest
  password: guest
